apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rest-api-ingress
spec:
  tls:
  - hosts:
      - api.quotable.io
    secretName: rest-api-tls
  rules:
  - host: api.quotable.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rest-api
            port:
              number: 80
