apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
spec:
  tls:
  - hosts:
      - www.quotable.io
    secretName: webapp-tls
  rules:
  - host: www.quotable.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: quote-react-app
            port:
              number: 80
