apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-react-deployment
  labels:
    app: first-react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: first-react-app
  template:
    metadata:
      labels:
        app: first-react-app
    spec:
      containers:
      - name: first-react-app
        image: docker.io/library/first-react-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
