apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-react-deployment
  labels:
    app: quotebook-react-app
spec:
  replicas: {{ .Values.replicaCountWebApp }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: quotebook-react-app
  template:
    metadata:
      labels:
        app: quotebook-react-app
    spec:
      containers:
      - name: quote-react-app
        env:
          - name: REST_API_URL
            valueFrom:
              configMapKeyRef:
                name: ui-config-map
                key: REST_API_URL
          - name: REACT_APP_REST_API_URL
            valueFrom:
              configMapKeyRef:
                name: ui-config-map
                key: REST_API_URL2
        image: lordoverkirk/quotable:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
