apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-react-deployment
  labels:
    app: quotebook-react-app
spec:
  replicas: {{ .Values.replicaCountWebApp }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: quotebook-react-app
  template:
    metadata:
      labels:
        app: quotebook-react-app
    spec:
      containers:
      - name: quote-react-app
        image: lordoverkirk/quotable:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
