kind: Service
apiVersion: v1
metadata:
  name: rest-api
  labels:
    app: quotebook-rest-api
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: quotebook-rest-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotebook-rest-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: quotebook-rest-api
    spec:
      containers:
      - image: cloone8/quotebook-rest-api:v1
        imagePullPolicy: Always
        name: rest-api
        envFrom:
          - configMapRef:
              name: rest-api-config
        env:
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: rest-api-secret
                key: DB_PASS
        ports:
          - containerPort: 8080
            name: api
