apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-react-app
  labels:
    app: quote-react-app
spec:
  replicas: 4
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: quote-react-app
  template:
    metadata:
      labels:
        app: quote-react-app
        version: v1.0.0
    spec:
      containers:
      - name: quote-react-app
        image: lordoverkirk/quotable:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
